/**
 * File Generated by Sideko (sideko.dev)
 */
import { CoreResourceClient, CoreClient } from "visa_click_to_pay/core";
import { TransactionClient } from "visa_click_to_pay/resources/wallet/src/transaction";
import { ConfirmationsClient } from "visa_click_to_pay/resources/wallet/src/confirmations";

export class SrcClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  transaction: TransactionClient;
  confirmations: ConfirmationsClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.transaction = new TransactionClient(this._client);
    this.confirmations = new ConfirmationsClient(this._client);
  }

  // register api methods (keep comment for code generation)
}
