/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  payloadTypeIndicator?: string;
  recipientId?: string;
  serviceId?: string;
  srcClientId?: string;
  srcCorrelationId?: string;
  srcDpaId?: string;
  srciTransactionId?: string;
};
