/**
 * File Generated by Sideko (sideko.dev)
 */

export enum AdditionalAmountAdditionalAmountTypeEnum {
  Tip = "TIP",
  ConvenienceFee = "CONVENIENCE_FEE",
  ConvenienceFeePercentage = "CONVENIENCE_FEE_PERCENTAGE",
  SubTotal = "SUB_TOTAL",
}
