/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type AdditionalAmount = {
  additionalAmountType: types.AdditionalAmountAdditionalAmountTypeEnum;
  additionalAmountValue: string;
};
