/**
 * File Generated by Sideko (sideko.dev)
 */

export enum Address2VerificationStatusEnum {
  NotVerified = "NOT_VERIFIED",
  Verified = "VERIFIED",
  Failed = "FAILED",
  Changed = "CHANGED",
  ConsumerOverride = "CONSUMER_OVERRIDE",
}
