/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type Address2 = {
  accepted?: boolean;
  additionalLocation?: string;
  addressVerificationStatusOverride?: types.Address2AddressVerificationStatusOverrideEnum;
  billingAccepted?: boolean;
  changed?: string[];
  city?: string;
  countryCode: string;
  county?: string;
  default?: boolean;
  failed?: string[];
  firstName?: string;
  id: string;
  lastName?: string;
  lastUpdateTimestamp?: string;
  line1?: string;
  line1Raw?: string;
  line2?: string;
  line3?: string;
  masked?: boolean;
  neighborhood?: string;
  nickName?: string;
  personName?: string;
  phone?: string;
  phoneNumberCountryAlpha2Code?: string;
  phoneNumberCountryCode?: string;
  pointOfReference?: string;
  postalCode?: string;
  stateProvinceCode?: string;
  streetName?: string;
  streetNumber?: string;
  verificationStatus?: types.Address2VerificationStatusEnum;
  verified?: string[];
};
