/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type Address1 = {
  accepted?: boolean;
  additionalLocation?: string;
  addressLine1Raw?: string;
  addressVerificationStatusOverride?: types.Address1AddressVerificationStatusOverrideEnum;
  city?: string;
  countryCode: string;
  county?: string;
  default?: boolean;
  disableNotification?: string;
  id?: string;
  line1?: string;
  line2?: string;
  line3?: string;
  neighborhood?: string;
  nickName?: string;
  personName?: string;
  phone?: string;
  phoneNumberCountryAlpha2Code?: string;
  phoneNumberCountryCode?: string;
  pointOfReference?: string;
  postalCode?: string;
  stateProvinceCode?: string;
  streetName?: string;
  streetNumber?: string;
  verificationStatus?: types.Address1VerificationStatusEnum;
};
