/**
 * File Generated by Sideko (sideko.dev)
 */

export enum Address1AddressVerificationStatusOverrideEnum {
  NotVerified = "NOT_VERIFIED",
  Verified = "VERIFIED",
  ConsumerOverride = "CONSUMER_OVERRIDE",
}
