/**
 * File Generated by Sideko (sideko.dev)
 */

export type AssuranceData = {
  cardVerificationEntity?: string;
  cardVerificationMethod?: string;
  cardVerificationResults?: string;
  cardholderVerificationResults?: string;
  consumerVerificationResults?: string;
};
