/**
 * File Generated by Sideko (sideko.dev)
 */

export type AssuranceData2 = {
  cardAssuranceData?: string;
  cardVerificationEntity?: string;
  cardVerificationMethod?: string;
  cardVerificationResults?: string;
  cardVerificationTimestamp?: string;
  cardholderAssuranceData?: string;
  cardholderAuthenticationEntity?: string;
  cardholderAuthenticationMethod?: string;
  cardholderAuthenticationResults?: string;
  cardholderAuthenticationTimestamp?: string;
  cardholderVerificationResults?: string;
  consumerAssuranceData?: string;
  consumerVerificationEntity?: string;
  consumerVerificationMethod?: string;
  consumerVerificationResults?: string;
  consumerVerificationTimestamp?: string;
  deviceAssuranceData?: string;
  deviceVerificationEntity?: string;
  deviceVerificationMethod?: string;
  deviceVerificationResults?: string;
  deviceVerificationTimestamp?: string;
  relationshipAssuranceData?: string;
  relationshipVerificationEntity?: string;
  relationshipVerificationMethod?: string;
  relationshipVerificationResults?: string;
  relationshipVerificationTimestamp?: string;
};
