/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type AuthenticationData1 = {
  cavv: string;
  eciDescription: string;
  eciRaw: string;
  paresStatus: types.AuthenticationData1ParesStatusEnum;
  paresTimestamp: string;
  signatureVerification: string;
  veresEnrolled: types.AuthenticationData1VeresEnrolledEnum;
  veresTimestamp: string;
  xid?: string;
};
