/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type BillingConstraints1 = {
  acceptedRegions?: types.BillingRegions1;
  collectBillingAddress?: string;
};
