/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type CheckoutRequest3 = {
  assuranceData?: types.AssuranceData2;
  authorization?: string;
  checkoutRequestJws?: string;
  checkoutResponseUri?: string;
  complianceSettings?: types.ComplianceSettings;
  consumerId?: string;
  customInputData?: types.NvPairs;
  dpaData?: types.DpaData2;
  dpaTransactionOptions?: types.DpaTransactionOptions3;
  payloadTypeIndicatorCheckout?: types.CheckoutRequest3PayloadTypeIndicatorCheckoutEnum;
  payloadTypeIndicatorPayload?: types.CheckoutRequest3PayloadTypeIndicatorPayloadEnum;
  profileName?: string;
  recipientIdCheckout?: string;
  recipientIdPayload?: string;
  serviceId?: string;
  shippingAddress?: types.Address2;
  shippingAddressId?: string;
  shippingAddressIds?: string[];
  srcClientId?: string;
  srcCorrelationId?: string;
  srcDigitalCardId?: string;
  srcDpaId?: string;
  srcInitiatorId?: string;
  srciTransactionId?: string;
};
