/**
 * File Generated by Sideko (sideko.dev)
 */

export enum CheckoutRequest3PayloadTypeIndicatorPayloadEnum {
  Summary = "SUMMARY",
  Full = "FULL",
  Payment = "PAYMENT",
  NonPayment = "NON_PAYMENT",
}
