/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type ComplianceSettings = {
  cookie?: types.Consent;
  geoLocation?: types.Consent;
  privacy?: types.Consent;
  tnc?: types.Consent;
};
