/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type ConsumerInputData = {
  billNumber?: string;
  customInputData?: types.KeyValueData[];
  customerLabel?: string;
  loyaltyNumber?: string;
  mobileNumber?: string;
  purposeOfTransaction?: string;
  referenceLabel?: string;
  storeLabel?: string;
  terminalLabel?: string;
};
