/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type DigitalCardData = {
  artHeight?: number;
  artUri?: string;
  artWidth?: number;
  descriptorName?: string;
  pendingEvents?: types.DigitalCardDataPendingEventsItemEnum[];
  presentationName?: string;
  status: types.DigitalCardDataStatusEnum;
};
