/**
 * File Generated by Sideko (sideko.dev)
 */

export enum DigitalCardFeatureContentTypeEnum {
  TextString = "TEXT_STRING",
  ImageUrl = "IMAGE_URL",
  ContentUrl = "CONTENT_URL",
  LinkUrl = "LINK_URL",
}
