/**
 * File Generated by Sideko (sideko.dev)
 */

export enum DigitalCardDataPendingEventsItemEnum {
  PendingAvs = "PENDING_AVS",
  PendingSca = "PENDING_SCA",
  PendingConsumerIdv = "PENDING_CONSUMER_IDV",
  PendingBillingPhoneNumber = "PENDING_BILLING_PHONE_NUMBER",
}
