/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type DigitalCardFeature = {
  content: string;
  contentType: types.DigitalCardFeatureContentTypeEnum;
  height?: number;
  style?: string;
  width?: number;
};
