/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type DpaTransactionOptions3 = {
  acquirerId?: string;
  acquirerMid?: string;
  additionalSellerData?: types.AdditionalSellerData;
  consumerEmailAddressRequested?: boolean;
  consumerInputData?: types.ConsumerInputData;
  consumerNameRequested?: boolean;
  consumerNationalIdentifierRequested?: boolean;
  consumerPhoneNumberRequested?: boolean;
  customInputData?: types.NvPairs;
  dpaAcceptedBillingCountries?: string[];
  dpaAcceptedShippingCountries?: string[];
  dpaBillingPreference?: types.DpaTransactionOptions3DpaBillingPreferenceEnum;
  dpaLocale?: string;
  dpaName?: string;
  dpaShippingPreference?: types.DpaTransactionOptions3DpaShippingPreferenceEnum;
  dynamicDataType?: types.DpaTransactionOptions3DynamicDataTypeEnum;
  merchantCategoryCode?: string;
  merchantChannel?: string;
  merchantCountryCode?: string;
  merchantOrderId?: string;
  orderType?: string;
  paymentOptions?: types.PaymentOptions2[];
  sellerPresentedData?: types.SellerPresentedData;
  srcTokenRequestData?: types.NvPairs;
  threeDsInputData?: types.ThreeDsInputData;
  threeDsPreference?: types.DpaTransactionOptions3ThreeDsPreferenceEnum;
  transactionAmount?: types.TransactionAmount2;
  transactionType?: types.DpaTransactionOptions3TransactionTypeEnum;
};
