/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type DpaData2 = {
  applicationType?: types.DpaData2ApplicationTypeEnum;
  dpaAddress?: types.SrcAddress;
  dpaEmailAddress?: string;
  dpaLogoUri?: string;
  dpaName: string;
  dpaPhoneNumber?: types.PhoneNumber;
  dpaPresentationName?: string;
  dpaSupportEmailAddress?: string;
  dpaSupportPhoneNumber?: types.PhoneNumber;
  dpaSupportUri?: string;
  dpaUri?: string;
  merchantAccountInformation?: string;
  terminalData?: types.TerminalData;
};
