/**
 * File Generated by Sideko (sideko.dev)
 */

export enum DpaTransactionOptions3DynamicDataTypeEnum {
  CardApplicationCryptogramShortForm = "CARD_APPLICATION_CRYPTOGRAM_SHORT_FORM",
  CardApplicationCryptogramLongForm = "CARD_APPLICATION_CRYPTOGRAM_LONG_FORM",
  DynamicCardSecurityCode = "DYNAMIC_CARD_SECURITY_CODE",
  CardholderAuthenticationCryptogram = "CARDHOLDER_AUTHENTICATION_CRYPTOGRAM",
  CardApplicationCryptogramOther = "CARD_APPLICATION_CRYPTOGRAM_OTHER",
  None = "NONE",
}
