/**
 * File Generated by Sideko (sideko.dev)
 */

export enum DpaTransactionOptions3TransactionTypeEnum {
  Purchase = "PURCHASE",
  BillPayment = "BILL_PAYMENT",
  MoneyTransfer = "MONEY_TRANSFER",
  Disbursement = "DISBURSEMENT",
  P2P = "P_2_P",
}
