/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type GetPaymentDataResponse1 = {
  creationTimeStamp?: string;
  encKey?: string;
  encPaymentData?: string;
  expiryTimeStamp?: string;
  externalClientId?: string;
  idValidationSessionId?: string;
  intentId?: string;
  maskedValidationChannel?: types.IdentityValidationChannel1;
  newUser?: boolean;
  partialPaymentInstrument?: types.PartialPaymentInstrument1;
  partialShippingAddress?: types.PartialShippingAddress1;
  paymentInstrument?: types.PaymentInstrument1;
  paymentMethodType?: types.GetPaymentDataResponse1PaymentMethodTypeEnum;
  paymentRequest?: types.PaymentRequest1;
  responseStatus?: types.ResponseStatus1;
  riskData?: types.RiskData1;
  shippingAddress?: types.Address1;
  supportedValidationChannels?: types.IdentityValidationChannel1[];
  threeDS?: types.AuthenticationData1;
  userData?: types.UserData1;
  visaCheckoutGuest?: boolean;
  walletInfo?: types.WalletInfo1;
};
