/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type IdentityValidationChannel1 = {
  identityProvider?: types.IdentityValidationChannel1IdentityProviderEnum;
  identityType?: types.IdentityValidationChannel1IdentityTypeEnum;
  maskedValidationChannel?: string;
  validationChannelId?: string;
};
