/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type MaskedCard = {
  cardBrand?: string;
  countryCode?: string;
  dateOfCardCreated?: string;
  dateOfCardLastUsed?: string;
  dateofCardCreated?: string;
  dateofCardLastUsed?: string;
  dcf?: types.Dcf;
  digitalCardData?: types.DigitalCardData;
  digitalCardFeatures?: types.DigitalCardFeature[];
  eligible?: boolean;
  maskedBillingAddress?: types.SrcAddress;
  network?: string;
  panBin?: string;
  panExpirationMonth?: string;
  panExpirationYear?: string;
  panLastFour?: string;
  paymentAccountReference?: string;
  paymentCardDescriptor?: string;
  paymentCardType?: string;
  serviceId?: string;
  srcDigitalCardId: string;
  srcPaymentCardId?: string;
  tokenBinRange?: string;
  tokenLastFour?: string;
};
