/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type MaskedConsumerIdentity = {
  identityProvider?: types.MaskedConsumerIdentityIdentityProviderEnum;
  identityType: types.MaskedConsumerIdentityIdentityTypeEnum;
  maskedIdentityValue: string;
};
