/**
 * File Generated by Sideko (sideko.dev)
 */

export enum MerchantIntentConfig1DatalevelEnum {
  Summary = "SUMMARY",
  Full = "FULL",
  Payment = "PAYMENT",
  NonPayment = "NON_PAYMENT",
  None = "NONE",
}
