/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PartialPaymentInstrument1 = {
  lastFourDigits: string;
  paymentType: types.PaymentType1;
};
