/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PaymentRequest1EventSourceEnum {
  Consumer = "CONSUMER",
  LightboxTw = "LIGHTBOX_TW",
  Lightbox = "LIGHTBOX",
  Issuer = "ISSUER",
  ThirdPartyWallet = "THIRD_PARTY_WALLET",
}
