/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PaymentConstraints1 = {
  acceptCanadianVISADebit?: boolean;
  paymentCurrency?: string;
  paymentTypes: types.AcceptedPaymentTypes1;
};
