/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PaymentInstrument1VerificationStatusEnum {
  NotVerified = "NOT_VERIFIED",
  Verified = "VERIFIED",
  Failed = "FAILED",
  Changed = "CHANGED",
  ConsumerOverride = "CONSUMER_OVERRIDE",
  Rejected = "REJECTED",
  Error = "ERROR",
}
