/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PaymentType1CardTypeEnum {
  Credit = "CREDIT",
  Debit = "DEBIT",
  Charge = "CHARGE",
  DebitCredit = "DEBIT_CREDIT",
  None = "NONE",
  Prepaid = "PREPAID",
  DeferredDebit = "DEFERRED_DEBIT",
}
