/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PaymentRequest1ChannelEnum {
  Web = "WEB",
  MobileWeb = "MOBILE_WEB",
  MobileSdk = "MOBILE_SDK",
  MobileQrCode = "MOBILE_QR_CODE",
  MobileNfc = "MOBILE_NFC",
}
