/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PaymentRequest1 = {
  buttonAction?: string;
  channel: types.PaymentRequest1ChannelEnum;
  countryCode?: string;
  currencyCode?: string;
  customData?: types.NvPairs1;
  description?: string;
  discount?: string;
  eventSource: types.PaymentRequest1EventSourceEnum;
  giftWrap?: string;
  locale?: string;
  merchantConfig?: types.MerchantIntentConfig1;
  merchantRequestId?: string;
  misc?: string;
  orderId?: string;
  promoCode?: string;
  referenceCallID?: string;
  reviewMessage?: string;
  shippingHandling?: string;
  sourceId?: string;
  subtotal?: string;
  tax?: string;
  threeDSTxnAuthenticationRequired?: boolean;
  total?: string;
};
