/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyAssuranceData = {
  cardVerificationResults?: string;
  cardholderVerificationResults?: string;
  consumerVerificationResults?: string;
};
