/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataResponse500 = {
  entity?: Record<string, any>;
  metadata?: Record<string, any>;
  status?: number;
};
