/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataDpaAddress = {
  addressId?: string;
  city?: string;
  countryCode?: string;
  createTime?: string;
  lastUsedTime?: string;
  line1?: string;
  line2?: string;
  line3?: string;
  name?: string;
  state?: string;
  zip?: string;
};
