/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataDpaSupportPhoneNumber =
  {
    countryCode?: string;
    phoneNumber?: string;
  };
