/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsThreeDsPreferenceEnum {
  None = "NONE",
  Self = "SELF",
  Onbehalf = "ONBEHALF",
}
