/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaData = {
  applicationType?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataApplicationTypeEnum;
  dpaAddress?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataDpaAddress;
  dpaEmailAddress?: string;
  dpaLogoUri?: string;
  dpaName: string;
  dpaPhoneNumber?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataDpaPhoneNumber;
  dpaPresentationName?: string;
  dpaSupportEmailAddress?: string;
  dpaSupportPhoneNumber?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataDpaSupportPhoneNumber;
  dpaSupportUri?: string;
  dpaUri?: string;
};
