/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponseResponseStatus =
  {
    code?: number;
    details?: types.PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponseResponseStatusDetailsItem[];
    info?: string;
    message?: string;
    serviceResponseCode?: string;
    severity?: types.PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponseResponseStatusSeverityEnum;
    status?: number;
  };
