/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsDpaBillingPreferenceEnum {
  None = "NONE",
  Full = "FULL",
  PostalCountry = "POSTAL_COUNTRY",
}
