/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponseResponseStatusDetailsItemSeverityEnum {
  Error = "ERROR",
  Warning = "WARNING",
  Info = "INFO",
}
