/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsPaymentOptionsItemDynamicDataTypeEnum {
  CardApplicationCryptogramShortForm = "CARD_APPLICATION_CRYPTOGRAM_SHORT_FORM",
  CardApplicationCryptogramLongForm = "CARD_APPLICATION_CRYPTOGRAM_LONG_FORM",
  DynamicCardSecurityCode = "DYNAMIC_CARD_SECURITY_CODE",
  CardholderAuthenticationCryptogram = "CARDHOLDER_AUTHENTICATION_CRYPTOGRAM",
  None = "NONE",
}
