/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponse =
  {
    checkoutResponseJws: string;
    responseStatus?: types.PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponseResponseStatus;
  };
