/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptions =
  {
    consumerEmailAddressRequested?: boolean;
    consumerNameRequested?: boolean;
    consumerPhoneNumberRequested?: boolean;
    customInputData?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsCustomInputData;
    dpaAcceptedBillingCountries?: Record<string, any>[];
    dpaAcceptedShippingCountries?: Record<string, any>[];
    dpaBillingPreference?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsDpaBillingPreferenceEnum;
    dpaLocale?: string;
    dpaShippingPreference?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsDpaShippingPreferenceEnum;
    merchantCategoryCode?: string;
    merchantCountryCode?: string;
    merchantOrderId?: string;
    orderType?: string;
    paymentOptions?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsPaymentOptionsItem[];
    srcTokenRequestData?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsSrcTokenRequestData;
    threeDsInputData?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsThreeDsInputData;
    threeDsPreference?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsThreeDsPreferenceEnum;
    transactionAmount?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsTransactionAmount;
    transactionType?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsTransactionTypeEnum;
  };
