/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataBodyDpaDataApplicationTypeEnum {
  WebBrowser = "WEB_BROWSER",
  MobileApp = "MOBILE_APP",
  IotDevice = "IOT_DEVICE",
  Other = "OTHER",
}
