/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataBodyPayloadTypeIndicatorPayloadEnum {
  Summary = "SUMMARY",
  Full = "FULL",
  Payment = "PAYMENT",
  NonPayment = "NON_PAYMENT",
}
