/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsDpaShippingPreferenceEnum {
  None = "NONE",
  Full = "FULL",
  PostalCountry = "POSTAL_COUNTRY",
}
