/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type PostWalletPaymentsSrcTransactionPreparedataBody = {
  assuranceData?: types.PostWalletPaymentsSrcTransactionPreparedataBodyAssuranceData;
  authorization?: string;
  checkoutResponseUri?: string;
  consumerId?: string;
  customInputData?: types.PostWalletPaymentsSrcTransactionPreparedataBodyCustomInputData;
  dpaData?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaData;
  dpaTransactionOptions?: types.PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptions;
  payloadTypeIndicatorCheckout?: types.PostWalletPaymentsSrcTransactionPreparedataBodyPayloadTypeIndicatorCheckoutEnum;
  payloadTypeIndicatorPayload?: types.PostWalletPaymentsSrcTransactionPreparedataBodyPayloadTypeIndicatorPayloadEnum;
  recipientIdCheckout?: string;
  recipientIdPayload?: string;
  serviceId?: string;
  shippingAddressIds?: Record<string, any>[];
  srcClientId?: string;
  srcCorrelationId?: string;
  srcDigitalCardId?: string;
  srcDpaId?: string;
  srcInitiatorId?: string;
  srciTransactionId?: string;
};
