/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostWalletPaymentsSrcTransactionPreparedataResponseCheckoutResponseResponseStatusSeverityEnum {
  Error = "ERROR",
  Warning = "WARNING",
  Info = "INFO",
}
