/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsTransactionAmount =
  {
    transactionAmount?: number;
    transactionCurrencyCode?: string;
  };
