/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsCustomInputDataNvPairsItem =
  {
    name?: string;
    value?: string;
  };
