/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsThreeDsInputData =
  {
    acquirerId?: string;
    acquirerMid?: string;
    requestorId?: string;
  };
