/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostWalletPaymentsSrcTransactionPreparedataBodyDpaTransactionOptionsSrcTokenRequestDataNvPairsItem =
  {
    name?: string;
    value?: string;
  };
