/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type Response1 = {
  entity?: Record<string, any>;
  metadata?: types.Response1Metadata;
  status?: number;
};
