/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type ResponseStatus1 = {
  code?: number;
  details?: types.StatusDetailsEntry1[];
  info?: string;
  message?: string;
  serviceResponseCode?: string;
  severity?: types.ResponseStatus1SeverityEnum;
  status?: number;
};
