/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type ResponseStatus = {
  code?: number;
  details?: types.StatusDetailsEntry[];
  info?: string;
  message?: string;
  serviceResponseCode?: string;
  severity?: types.ResponseStatusSeverityEnum;
  status?: number;
};
