/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type Response = {
  entity?: Record<string, any>;
  metadata?: types.ResponseMetadata;
  status?: number;
};
