/**
 * File Generated by Sideko (sideko.dev)
 */

export type RiskData1 = {
  advice: string;
  ageOfAccount?: number;
  avsResponseCode: string;
  code: string;
  cvvResponseCode: string;
  firstUseAuthenticated?: boolean;
  score?: number;
};
