/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type SaveConfirmationDetailsRequest = {
  confirmationData: types.ConfirmationData;
  serviceId?: string;
  srcClientId: string;
  srcCorrelationId: string;
  srcDpaId?: string;
  srciTransactionId?: string;
};
