/**
 * File Generated by Sideko (sideko.dev)
 */

export type ShippingAddress1 = {
  addressLine1: string;
  addressLine2: string;
  city: string;
  id: string;
  personName?: string;
  postalCode: string;
  stateProvinceCode: string;
};
