/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type ShippingConstraints1 = {
  acceptedRegions?: types.ShippingRegions1;
  collectShipping?: boolean;
};
