/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type SrcConsumer = {
  complianceSettings?: types.ComplianceSettings;
  consumerIdentity?: types.SrcConsumerConsumerIdentityEnum;
  countryCode?: string;
  dateConsumerAdded: string;
  dateConsumerLastUsed?: string;
  emailAddress?: string;
  firstName?: string;
  fullName: string;
  languageCode?: string;
  lastName?: string;
  maskedConsumerIdentity?: types.MaskedConsumerIdentity;
  maskedEmailAddress?: string;
  maskedFirstName?: string;
  maskedFullName?: string;
  maskedLastName?: string;
  maskedMobileNumber?: types.PhoneNumber;
  maskedNationalIdentifier?: string;
  mobileNumber?: types.PhoneNumber;
  nationalIdentifier?: string;
  srcConsumerId?: string;
  status?: string;
};
