/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type StatusDetailsEntry = {
  code?: string;
  message: string;
  name: string;
  severity: types.StatusDetailsEntrySeverityEnum;
};
