/**
 * File Generated by Sideko (sideko.dev)
 */

export type ThreeDsSetup1 = {
  acquirerId?: string;
  acquirerMid?: string;
  requestorId?: string;
  threeDSActive?: boolean;
  threeDSSuppressChallenge?: boolean;
};
