/**
 * File Generated by Sideko (sideko.dev)
 */

export enum TokenizationSetup1TokenCryptogramTypeEnum {
  Dtvv = "DTVV",
  Tavv = "TAVV",
  CardApplicationCryptogramShortForm = "CARD_APPLICATION_CRYPTOGRAM_SHORT_FORM",
  CardApplicationCryptogramLongForm = "CARD_APPLICATION_CRYPTOGRAM_LONG_FORM",
  DynamicCardSecurityCode = "DYNAMIC_CARD_SECURITY_CODE",
  None = "NONE",
}
