/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "visa_click_to_pay/types";

export type TransactionAmount2 = {
  additionalAmounts?: types.AdditionalAmount[];
  transactionAmount?: number;
  transactionCurrencyCode?: string;
};
