/**
 * File Generated by Sideko (sideko.dev)
 */

export type UserData1 = {
  encUserId: string;
  userEmail: string;
  userFirstName: string;
  userFullName: string;
  userLastName: string;
  userName: string;
  userPersonalId?: string;
};
