/**
 * File Generated by Sideko (sideko.dev)
 */

export type GetRequest = {
  callId: string;
  dataLevel?: string;
  encryptionKey?: string;
  externalClientId?: string;
  payloadType?: string;
  tokenCryptogramType?: string;
};

export type PutRequest = {
  callId: string;
};
