/**
 * File Generated by Sideko (sideko.dev)
 */
import { CoreResourceClient, CoreClient } from "visa_click_to_pay/core";
import { PaymentsClient } from "visa_click_to_pay/resources/wallet/payments";
import { SrcClient } from "visa_click_to_pay/resources/wallet/src";

export class WalletClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  payments: PaymentsClient;
  src: SrcClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.payments = new PaymentsClient(this._client);
    this.src = new SrcClient(this._client);
  }

  // register api methods (keep comment for code generation)
}
