/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "visa_click_to_pay/core";
import * as requests from "visa_click_to_pay/resources/wallet/src/confirmations/request-types";

export class ConfirmationsClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * API to retrieve the transaction payload. This API is based off of EMVCo 1.0 DRAFT spec and is expected to be invoked by a Non-Visa SRCI
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<null> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "post",
      path: "/wallet/src/confirmations",
      contentType: "application/json",
      body: request.data,
      responseType: "json",
      opts,
    });
  }
}
