/**
 * File Generated by Sideko (sideko.dev)
 */
import { CoreResourceClient, CoreClient } from "visa_click_to_pay/core";
import { TransactionClient } from "visa_click_to_pay/resources/wallet/payments/src/transaction";

export class SrcClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  transaction: TransactionClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.transaction = new TransactionClient(this._client);
  }

  // register api methods (keep comment for code generation)
}
